version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: aethron-api-app
    container_name: aethron-app
    restart: unless-stopped
    working_dir: /var/www
    entrypoint: [ "sh", "./docker/entrypoint.sh" ]
    volumes:
      - ./:/var/www
    networks:
      - aethron-network

  webserver:
    image: nginx:alpine
    container_name: aethron-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - aethron-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: aethron-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - aethron-network
    ports:
      - "33061:3306"

  redis:
    image: redis:alpine
    container_name: aethron-redis
    restart: unless-stopped
    networks:
      - aethron-network
    ports:
      - "63791:6379"

networks:
  aethron-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
